language:
  - c

env:
  - C_STANDARD=99 CXX_STANDARD=98

matrix:
  include:
#    - os: linux
#      dist: trusty
#      compiler: clang-3.6
#      addons:
#        apt:
#          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty']
#          packages: clang-3.6
#
#    - os: linux
#      dist: trusty
#      compiler: clang
#      addons:
#        apt:
#          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty']
#          packages: clang-3.4
#
#    - os: linux
#      dist: trusty
#      compiler: gcc-4.4
#      addons:
#        apt:
#          sources: ubuntu-toolchain-r-test
#          packages: gcc-4.4
#
#    - os: linux
#      dist: trusty
#      compiler: gcc-4.7
#      addons:
#        apt:
#          sources: ubuntu-toolchain-r-test
#          packages: gcc-4.7
#
#    - os: linux
#      dist: trusty
#      compiler: gcc-4.8
#      addons:
#        apt:
#          sources: ubuntu-toolchain-r-test
#          packages: gcc-4.8

    - os: linux
      dist: trusty
      compiler: gcc-4.9
      addons:
        apt:
          sources: ubuntu-toolchain-r-test
          packages: gcc-4.9

    - os: linux
      dist: trusty
      compiler: gcc-5
      addons:
        apt:
          sources: ubuntu-toolchain-r-test
          packages: gcc-5
      # coverage build
      install:
        - cd ${TRAVIS_BUILD_DIR}
        - wget http://ftp.de.debian.org/debian/pool/main/l/lcov/lcov_1.11.orig.tar.gz
        - tar xf lcov_1.11.orig.tar.gz
        - sudo make -C lcov-1.11/ install
        - gem install coveralls-lcov
      after_success:
        - cd ${TRAVIS_BUILD_DIR}
        - lcov --directory . -b ./src --capture --output-file coverage.info
        - lcov --remove coverage.info 'tests/*' '/usr/*' --output-file coverage.info
        - lcov --list coverage.info
        - coveralls-lcov --repo-token ${COVERALLS_TOKEN} coverage.info

    - os: linux
      dist: trusty
      compiler: gcc-6
      addons:
        apt:
          sources: ubuntu-toolchain-r-test
          packages: gcc-6
      env:
        - C_STANDARD=90

#    - os: linux
#      dist: trusty
#      compiler: gcc-6
#      addons:
#        apt:
#          sources: ubuntu-toolchain-r-test
#          packages: gcc-6
#      env:
#        - C_STANDARD=11
#
#    - os: linux
#      dist: trusty
#      compiler: gcc-6
#      addons:
#        apt:
#          sources: ubuntu-toolchain-r-test
#          packages: gcc-6
#      env:
#        - CXX_STANDARD=11
#
#    - os: linux
#      dist: trusty
#      compiler: gcc-6
#      addons:
#        apt:
#          sources: ubuntu-toolchain-r-test
#          packages: gcc-6
#      env:
#        - CXX_STANDARD=14
#
#    - os: linux
#      dist: trusty
#      compiler: gcc-6
#      addons:
#        apt:
#          sources: ubuntu-toolchain-r-test
#          packages: gcc-6
#
#    - os: osx
#      osx_image: xcode7.3
#      compiler: gcc
#
#    - os: osx
#      osx_image: xcode8.3
#      compiler: gcc

script:
  - cd ${TRAVIS_BUILD_DIR}
  - ./travis.sh
