version: 0.5.1-{build}

platform: x64

environment:
  matrix:
    - COMPILER: mingw
      GENERATOR: MinGW Makefiles
      BUILD_TYPE: Debug
    - COMPILER: mingw
      GENERATOR: MinGW Makefiles
      BUILD_TYPE: Release
#    - COMPILER: msvc
#      GENERATOR: Visual Studio 14 2015 Win64
#      BUILD_TYPE: Debug
#    - COMPILER: msvc
#      GENERATOR: Visual Studio 14 2015
#      BUILD_TYPE: Debug

install:
  # otherwise MinGW will complain if git's sh.exe in path
  - set PATH=%PATH:C:\Program Files\Git\bin;=%
#  - if "%COMPILER%"=="mingw" set PATH=C:\MinGW\bin;%PATH%
#  - if "%COMPILER%"=="mingw" mingw-get update
#  - if "%COMPILER%"=="mingw" mingw-get install mingw32-gmp
#  - if "%COMPILER%"=="mingw" rename "C:\Program Files\Git\usr\bin\sh.exe" "sh2.exe"

build_script:
  - mkdir build
  - cd build
  - cmake -G "%GENERATOR%" ..
  - cmake --build .
  - ctest -V -C "%BUILD_TYPE%"

