version: 1.1.0-{build}

environment:
  matrix:
    - GENERATOR: MinGW Makefiles
      BUILD_TYPE: Debug
    - GENERATOR: Visual Studio 14 2015
      BUILD_TYPE: Debug
    - GENERATOR: Visual Studio 14 2015 Win64
      BUILD_TYPE: Debug

install:
  # install 64 bit mingw
  - ps: if (!(Test-Path c:\tools\mingw64) -and ([[ $GENERATOR -Contains "MinGW"]])) {
          echo "!!!!!!!"
          choco install -y mingw
          refreshenv
          SET PATH=%PATH%:C:\Program Files\Git\usr\bin;=%
        }

cache:
  - C:\tools\mingw64 -> appveyor.yml

build_script:
  - refreshenv
  # remove sh.exe from PATH for MinGW
  - set PATH=%PATH:C:\Program Files\Git\usr\bin;=%
  # remove 32 bit mingw from PATH
  - set PATH=%PATH:C:\MinGW\bin;=%
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=%BUILD_TYPE% -G "%GENERATOR%" ..
  - cmake --build .
  - ctest -V -C "%BUILD_TYPE%"

