version: 1.1.0-{build}

platform: x64

environment:
  matrix:
    - COMPILER: mingw
      GENERATOR: MinGW Makefiles
      BUILD_TYPE: Debug
    - COMPILER: mingw
      GENERATOR: MinGW Makefiles
      BUILD_TYPE: Release
    - COMPILER: msvc
      GENERATOR: Visual Studio 14 2015
      BUILD_TYPE: Debug
    - COMPILER: msvc
      GENERATOR: Visual Studio 14 2015 Win64
      BUILD_TYPE: Debug

install:
  - if "%COMPILER%"=="mingw" choco install -y mingw

build_script:
  - if "%COMPILER%"=="mingw" refreshenv
  - if "%COMPILER%"=="mingw" SET PATH=%PATH:C:\Program Files\Git\usr\bin;=%
  - if "%COMPILER%"=="mingw" mingw32-make
  - if "%COMPILER%"=="mingw" mingw32-make test

  - if "%COMPILER%"=="msvc" mkdir build
  - if "%COMPILER%"=="msvc" cd build
  - if "%COMPILER%"=="msvc" cmake -DCMAKE_BUILD_TYPE=%BUILD_TYPE% -G "%GENERATOR%" ..
  - if "%COMPILER%"=="msvc" cmake --build .
  - if "%COMPILER%"=="msvc" ctest -V -C "%BUILD_TYPE%"

