version: 1.1.0-{build}

environment:
  matrix:
    - GENERATOR: MinGW Makefiles
      BUILD_TYPE: Debug
    - GENERATOR: MinGW Makefiles
      BUILD_TYPE: Release
    - GENERATOR: Visual Studio 14 2015
      BUILD_TYPE: Debug
    - GENERATOR: Visual Studio 14 2015 Win64
      BUILD_TYPE: Debug

install:
  - choco install -y mingw
#  - cmd: if "%GENERATOR%"=="MinGW Makefiles" choco install -y mingw

build_script:
  - refreshenv
#  - cmd: if "%GENERATOR%"=="MinGW Makefiles" refreshenv
  - SET PATH=%PATH:C:\Program Files\Git\usr\bin;=%
  - cmd: if "%GENERATOR%"=="MinGW Makefiles" SET PATH=%PATH:C:\Program Files\Git\usr\bin;=%
  # remove 32 bit mingw from PATH
  - set PATH=%PATH:C:\MinGW\bin;=%
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=%BUILD_TYPE% -G "%GENERATOR%" ..
  - cmake --build .
  - ctest -V -C "%BUILD_TYPE%"

