version: 1.0.{build}

environment:
  matrix:
    - BUILD_TYPE: Release
      COMPILER: MSVC14
  
    - BUILD_TYPE: Release
      COMPILER: MSVC15

install:
  - cmd: echo 'Start install script'

build_script:
  - cmd: echo 'Start build script'
  - cmd: mkdir build
  - cmd: cd build
  - cmd: cmake ..
  - cmd: msbuild hello.sln
  - cmd: ctest -C "Debug"

