version: 1.1.0-{build}

platform: x64

environment:
  matrix:
    - GENERATOR: MinGW Makefiles
      BUILD_TYPE: Debug
    - GENERATOR: MinGW Makefiles
      BUILD_TYPE: Release
    - GENERATOR: Visual Studio 14 2015
      BUILD_TYPE: Debug
    - GENERATOR: Visual Studio 14 2015 Win64
      BUILD_TYPE: Debug

install:
  - if "%GENERATOR%"=="MinGW Makefiles" choco install -y mingw

build_script:
  - refreshenv
  - SET PATH=%PATH:C:\Program Files\Git\usr\bin;=%
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=%BUILD_TYPE% -G "%GENERATOR%" ..
  - cmake --build .
  - ctest -V -C "%BUILD_TYPE%"
  - get-command make
  - if "%GENERATOR%"=="MinGW Makefiles" echo %PATH%

