version: 0.5.1-{build}

environment:
  matrix:
    - COMPILER: mingw
      GENERATOR: MinGW Makefiles
      PLATFORM: Win32

    - COMPILER: mingw-w64
      GENERATOR: MinGW Makefiles
      PLATFORM: x64

    - COMPILER: msvc
      GENERATOR: Visual Studio 15 2017 Win64
      PLATFORM: x64

    - COMPILER: msvc
      GENERATOR: Visual Studio 15 2017
      PLATFORM: Win32

    - COMPILER: msvc
      GENERATOR: Visual Studio 14 2015 Win64
      PLATFORM: x64

    - COMPILER: msvc
      GENERATOR: Visual Studio 14 2015
      PLATFORM: Win32

install:
  - if "%COMPILER%"=="mingw" set PATH=C:\MinGW\bin;%PATH%
  - if "%COMPILER%"=="mingw-w64" set PATH=C:\mingw-w64\bin;%PATH%

build_script:
  - mkdir build
  - cd build
  - cmake -G "%GENERATOR%" -DCMAKE_SH=CMAKE_SH-NOTFOUND ..
  - cmake --build .
  - ctest -V

