version: 1.0.{build}

image: Visual Studio 2015

matrix:
  allow_failures:
    - platform: x86
    - platform: x64

install:
  - cmd: echo 'Start install script'

build_script:
  - cmd: echo 'Start build script'
#  - cmd: appveyor.sh
  - cmd: mkdir build
  - cmd: cd build
  - cmd: cmake ..
  - cmd: make
  - cmd: src/hello

