version: 1.0.{build}

environment:
  matrix:
    - COMPILER: MSVC14
#    - COMPILER: MSVC15
#    - COMPILER: MinGW

install:
  - cmd: choco install -y mingw

build_script:
#  - cmd: SET PATH=C:\mingw64\bin;%PATH%
  - cmd: refreshenv
  - cmd: ls C:\tools\mingw64\bin
#  - cmd: C:\msys64\usr\bin\sh.exe --login /c/projects
  - cmd: mkdir build
  - cmd: cd build
  - cmd: cmake ..
  - cmd: mingw32-make
  - cmd: ctest -C "Debug"

