version: 1.1.0-{build}

environment:
  matrix:
    - GENERATOR: MinGW Makefiles
    - GENERATOR: Visual Studio 14 2015
    - GENERATOR: Visual Studio 14 2015 Win64

configuration: Debug

build_script:
  # Workaround for CMake not wanting sh.exe on PATH for MinGW
  - set PATH=%PATH:C:\Program Files\Git\usr\bin;=%
  - set PATH=C:\MinGW\bin;%PATH%
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=%CONFIGURATION% -G "%GENERATOR%" ..
  - ctest -V

#build_script: cmake --build .. --config %CONFIGURATION%

