version: 1.0.{build}

environment:
  matrix:
    - COMPILER: MSVC14
    - COMPILER: MSVC15
    - COMPILER: MinGW

install:
  - cmd: echo 'Start install script'

build_script:
  - cmd: echo 'Start build script'
  - cmd: mkdir build
  - cmd: cd build
  - cmd: cmake ..
  - cmd: msbuild hello.sln
  - cmd: ctest -C "Debug"

