version: 1.0.{build}

environment:
  matrix:
    - COMPILER: MSVC14
#    - COMPILER: MSVC15
#    - COMPILER: MinGW

build_script:
  - cmd: mkdir build
  - cmd: cd build
  - cmd: cmake ..
  - cmd: msbuild hello.sln \p:Configuration="Release"
  - cmd: ctest -C "Release"

