version: 0.5.1-{build}

platform: x64

environment:
  matrix:
    - COMPILER: mingw
      GENERATOR: MinGW Makefiles
      BUILD_TYPE: Debug
    - COMPILER: mingw
      GENERATOR: MinGW Makefiles
      BUILD_TYPE: Release
    - COMPILER: msvc
      GENERATOR: Visual Studio 14 2015 Win64
      BUILD_TYPE: Debug
    - COMPILER: msvc
      GENERATOR: Visual Studio 14 2015
      BUILD_TYPE: Debug

install:
  - if "%COMPILER%"=="mingw" set PATH=C:\MinGW\bin;%PATH%

build_script:
  - mkdir build
  - cd build
  - cmake -G "%GENERATOR%" -DCMAKE_SH=CMAKE_SH-NOTFOUND ..
  - cmake --build .
  - ctest -V -C "%BUILD_TYPE%"

