version: 1.1.0-{build}

environment:
  matrix:
    - GENERATOR: MinGW Makefiles
      BUILD_TYPE: Debug
    - GENERATOR: Visual Studio 14 2015
      BUILD_TYPE: Debug
    - GENERATOR: Visual Studio 14 2015 Win64
      BUILD_TYPE: Debug

build_script:
  # Workaround for CMake not wanting sh.exe on PATH for MinGW
  - set PATH=%PATH:C:\Program Files\Git\usr\bin;=%
  - set PATH=C:\MinGW\bin;%PATH%
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=%BUILD_TYPE% -G "%GENERATOR%" ..
  - cmake --build .
  - ctest -V -C "%BUILD_TYPE%"

